### ISSUE TITLE
feat: support pull requests

### ISSUE THREAD

**Issue by robingenz** [imhoffd/needs-reply#8]
First of all: Thank you for this action! I use it in many repos and it is very helpful!

It would be great if this action could also support pull requests.

**Comment by kewisch** [comment]
It appears based on the code that pull requests are supported, is anything not working now or did this issue predate support?

**Comment by robingenz** [comment]
You're right. It works: https://github.com/capawesome-team/capacitor-plugins/pull/267 I'm not sure what didn't work when I created the issue.
